add_newline = false

[line_break]
disabled = false

[package]
disabled = true

[python]
format = 'via [${version}( \($virtualenv\))]($style) '
style = "blue bold"

# Hide the username. The username will only show in certain scenarios
[username]
disabled = false
show_always = true
format = "[$user]($style) on "

# shows the hostname on new lines
[hostname]
ssh_only = false
disabled = false
format =  "[$hostname](bold red) in "
style = "bold italic #87A752"

# configure directory
[directory]
truncation_length = 10
truncate_to_repo = true # truncates directory to root folder if in github repo
style = "bold italic #87A752"

[cmd_duration]
min_time = 500
show_milliseconds = false
disabled = false
style = "bold italic #87A752"
format = "\\[took [$duration](bold yellow)\\]"
